name: CI Android App

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Lint code
        run: ./gradlew lint
        continue-on-error: true

      - name: Run Tests
        run: ./gradlew test
        continue-on-error: true

      - name: Build project
        run: ./gradlew assemble
